[package]
name = "gameboy-emu-rs"
version = "0.1.0"
authors = ["Andrew Mellen <andy1030@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
